// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type ProgramInfo struct {
	ID             int64
	CreatedAt      int64
	UpdatedAt      int64
	Title          string
	Pi             string
	Eap            int64
	Primetime      float64
	Paralleltime   float64
	Instrumentmode string
	Programtype    string
}

type Visit struct {
	ID            int64
	CreatedAt     int64
	UpdatedAt     int64
	ProgramID     int64
	Observation   int64
	Visit         int64
	Status        string
	Target        string
	Configuration string
	Starttime     int64
	Endtime       int64
}
